import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";

const SRC = "surethan.jpg";
const OUT = "public/assets/images";
await mkdir(OUT, { recursive: true });

const meta = await sharp(SRC).metadata();
const W = meta.width, H = meta.height;
console.log(`source: ${W}x${H}`);

// Subject (fractions of frame, measured from the sunrise shot):
// center x ≈ 0.492, head top ≈ 0.50 of height, sun glow directly above head.
const cx = Math.round(W * 0.492);

// ---- 1. Portrait 4:5 — full height, subject + glow centered ----
{
  const cropH = H;
  const cropW = Math.round(cropH * 0.8);
  const left = Math.min(Math.max(cx - Math.round(cropW / 2), 0), W - cropW);
  await sharp(SRC)
    .extract({ left, top: 0, width: cropW, height: cropH })
    .resize(880, 1100, { kernel: "lanczos3" })
    .modulate({ saturation: 0.88, brightness: 1.02 })
    .sharpen({ sigma: 0.9 })
    .webp({ quality: 84 })
    .toFile(`${OUT}/portrait.webp`);
  console.log(`portrait.webp <- crop ${cropW}x${cropH} @${left},0`);
}

// ---- 2. Square 1:1 (nav/avatar fallback, tighter on subject) ----
{
  const cropH = Math.round(H * 0.72);
  const top = H - cropH;
  const cropW = cropH;
  const left = Math.min(Math.max(cx - Math.round(cropW / 2), 0), W - cropW);
  await sharp(SRC)
    .extract({ left, top, width: cropW, height: cropH })
    .resize(640, 640, { kernel: "lanczos3" })
    .modulate({ saturation: 0.88 })
    .webp({ quality: 84 })
    .toFile(`${OUT}/portrait-square.webp`);
  console.log(`portrait-square.webp <- crop ${cropW}x${cropH} @${left},${top}`);
}

// ---- 3. Cinematic wide 21:9 (contact band) ----
{
  const cropW = W;
  const cropH = Math.min(H, Math.round(W * (9 / 21)));
  const top = Math.min(Math.round(H * 0.30), H - cropH);
  await sharp(SRC)
    .extract({ left: 0, top, width: cropW, height: cropH })
    .resize(1800, Math.round(1800 * (9 / 21)), { kernel: "lanczos3" })
    .modulate({ saturation: 0.85 })
    .webp({ quality: 80 })
    .toFile(`${OUT}/sunrise-wide.webp`);
  console.log(`sunrise-wide.webp <- crop ${cropW}x${cropH} @0,${top}`);
}

// ---- 4. OG image 1200x630, dark graded + typographic overlay ----
{
  const base = await sharp(SRC)
    .resize(1200, 630, { fit: "cover", position: "attention" })
    .modulate({ brightness: 0.72, saturation: 0.8 })
    .toBuffer();
  const overlay = Buffer.from(`
    <svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0" stop-color="#0a0a0b" stop-opacity="0.25"/>
          <stop offset="1" stop-color="#0a0a0b" stop-opacity="0.92"/>
        </linearGradient>
      </defs>
      <rect width="1200" height="630" fill="url(#g)"/>
      <text x="72" y="470" font-family="Arial, Helvetica, sans-serif" font-size="88" font-weight="700" fill="#f4f4f5" letter-spacing="-2">SURETHAN S</text>
      <text x="72" y="530" font-family="Arial, Helvetica, sans-serif" font-size="30" fill="#a1a1aa">Product Engineer · AI Engineer · Frappe/ERPNext</text>
      <text x="72" y="576" font-family="Arial, Helvetica, sans-serif" font-size="30" fill="#22c55e">I ship production AI — not demos.</text>
      <circle cx="86" cy="120" r="7" fill="#34d399"/>
      <text x="108" y="128" font-family="monospace" font-size="22" fill="#34d399" letter-spacing="3">LIVE IN PRODUCTION</text>
    </svg>`);
  await sharp(base).composite([{ input: overlay }]).png().toFile(`${OUT}/og.png`);
  console.log("og.png");
}

// ---- 5. Blur placeholder (base64) for the portrait ----
{
  const buf = await sharp(`${OUT}/portrait.webp`).resize(16).webp({ quality: 30 }).toBuffer();
  const dataURL = `data:image/webp;base64,${buf.toString("base64")}`;
  await writeFile(
    "src/lib/image-meta.ts",
    `// generated by scripts/process-photo.mjs\nexport const portraitBlurDataURL =\n  "${dataURL}";\n`
  );
  console.log("blur placeholder ->", dataURL.length, "chars");
}
